//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleApp.AppData
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class dbTestEntities : DbContext
    {
        public dbTestEntities()
            : base("name=dbTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual int Sp_Login(string jsonInput, ObjectParameter jsonOutput, ObjectParameter errorCode)
        {
            var jsonInputParameter = jsonInput != null ?
                new ObjectParameter("JsonInput", jsonInput) :
                new ObjectParameter("JsonInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Sp_Login", jsonInputParameter, jsonOutput, errorCode);
        }
    }
}
